import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: ['bin/maestro.ts'],
    format: ['esm'],
    target: 'node20',
    outDir: 'dist/bin',
    clean: true,
    splitting: false,
    sourcemap: true,
    banner: {
      js: '#!/usr/bin/env node',
    },
  },
  {
    entry: [
      'src/templates/claude-md.ts',
      'src/templates/session-log.ts',
      'src/templates/session-index.ts',
      'src/templates/env-example.ts',
      'src/templates/gitignore.ts',
      'src/templates/readme.ts',
      'src/templates/architecture.ts',
      'src/templates/security.ts',
      'src/templates/brand-voice.ts',
      'src/templates/design-system.ts',
      'src/utils/fs.ts',
      'src/utils/format.ts',
      'src/utils/string-scanner.ts',
      'src/utils/sanitize-env.ts',
      'src/analyzers/types.ts',
      'src/analyzers/patterns.ts',
      'src/analyzers/context.ts',
      'src/analyzers/complexity.ts',
      'src/analyzers/complexity-function-length.ts',
      'src/analyzers/complexity-nesting.ts',
      'src/analyzers/dead-code.ts',
      'src/analyzers/structure.ts',
      'src/analyzers/hygiene.ts',
      'src/analyzers/consistency.ts',
      'src/analyzers/testing.ts',
      'src/analyzers/error-handling.ts',
      'src/analyzers/index.ts',
    ],
    format: ['esm'],
    target: 'node20',
    outDir: 'dist',
    dts: true,
    splitting: false,
    sourcemap: true,
  },
]);
